// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "themes",
    columns: [
      { name: "name", type: "text" },
      { name: "dateStart", type: "datetime" },
      { name: "year", type: "text" },
      { name: "description", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Themes = InferredTypes["themes"];
export type ThemesRecord = Themes & XataRecord;

export type DatabaseSchema = {
  themes: ThemesRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://lindgr3n-lhrlkl.eu-central-1.xata.sh/db/highcoast-gamejam",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
